# Generated by Django 5.0.3 on 2024-03-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0002_customers_delete_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterModelTable(
            name='customers',
            table='customers',
        ),
    ]
