# Generated by Django 5.0.3 on 2024-03-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_gateway', '0004_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='customer',
            field=models.CharField(max_length=50),
        ),
    ]
